"""benchprov command-line interface.

Subcommands: inspect, validate, stats, build.
Every subcommand supports --json for machine-readable output.
Exit codes: 0 = ok, 1 = validation errors / not found, 2 = usage or IO error.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from . import __version__
from .build import REGISTRY_REL, build
from .model import (
    CORE_DIMS,
    compute_state,
    find_repo_root,
    load_record_file,
    load_registry,
    load_sources,
    unknown_dimensions,
)
from .stats import registry_stats
from .validate import Report, Validator


# ------------------------------------------------------------------ helpers

def _fail(msg: str, code: int = 2) -> int:
    print(f"benchprov: {msg}", file=sys.stderr)
    return code


def _default_registry(root: Path | None) -> Path | None:
    if root is None:
        return None
    p = root / REGISTRY_REL
    return p if p.exists() else None


def _print_report(report: Report, as_json: bool) -> None:
    if as_json:
        print(json.dumps(
            {
                "ok": report.ok,
                "errors": [vars(f) for f in report.errors],
                "warnings": [vars(f) for f in report.warnings],
            },
            indent=2, ensure_ascii=False,
        ))
        return
    for f in report.findings:
        print(str(f))
    n_err, n_warn = len(report.errors), len(report.warnings)
    verdict = "PASS" if report.ok else "FAIL"
    print(f"{verdict}: {n_err} error(s), {n_warn} warning(s)")


# ------------------------------------------------------------------ validate

def cmd_validate(args: argparse.Namespace) -> int:
    root = find_repo_root()
    validator_root = root
    report = Report()
    validator = Validator(validator_root)

    if args.path is None:
        if root is None:
            return _fail("no path given and no benchprov data root found "
                         "(set BENCHPROV_ROOT or run inside the repository)")
        sources = load_sources(root)
        pairs = [(str(p.relative_to(root)), rec) for p, rec in sources.values()]
        for where, rec in pairs:
            validator.validate_record(rec, report, where=where)
        validator.validate_collection(pairs, report)
        check_report, _ = build(root, check_only=True)
        report.findings.extend(check_report.findings)
    else:
        path = Path(args.path)
        if not path.exists():
            return _fail(f"path not found: {path}")
        if path.is_dir():
            files = sorted(path.glob("*.json"))
            if not files:
                return _fail(f"no .json record files in {path}")
            pairs = [(str(p), load_record_file(p)) for p in files]
        elif path.suffix == ".jsonl":
            try:
                pairs = [(f"{path}:{i}", rec) for i, rec in enumerate(load_registry(path), start=1)]
            except ValueError as exc:
                return _fail(str(exc))
        else:
            pairs = [(str(path), load_record_file(path))]
        for where, rec in pairs:
            validator.validate_record(rec, report, where=where)
        validator.validate_collection(pairs, report)

    _print_report(report, args.json)
    return 0 if report.ok else 1


# ------------------------------------------------------------------ inspect

def _load_registry_records(args: argparse.Namespace) -> tuple[list[dict] | None, Path | None, int | None]:
    root = find_repo_root()
    reg_path = Path(args.registry) if getattr(args, "registry", None) else _default_registry(root)
    if reg_path is None or not reg_path.exists():
        return None, None, _fail(
            "no registry found (use --registry PATH, or run inside the benchprov repository)")
    try:
        return load_registry(reg_path), reg_path, None
    except ValueError as exc:
        return None, None, _fail(str(exc))


def _match_records(records: list[dict], query: str) -> list[dict]:
    exact_rid = [r for r in records if r["record_id"] == query]
    if exact_rid:
        return exact_rid
    exact_ds = [r for r in records if r["dataset"]["id"] == query]
    if exact_ds:
        return exact_ds
    q = query.lower()
    return [r for r in records if q in r["record_id"].lower() or q in r["dataset"]["id"].lower()]


_YESNO = {
    "machine": "YES — machine translated",
    "human": "NO — human translated",
    "hybrid_machine_post_edited": "PARTLY — machine translated, then human post-edited",
    "script_conversion": "NO — deterministic script conversion (but check the parent dataset)",
    "lm_generated": "NO — items generated by a language model (not a translation)",
    "native_original": "NO — natively authored in the target language(s)",
    "mixed": "MIXED — creation method varies within this dataset",
    "unknown": "UNKNOWN — no public evidence of creation method found",
}

_VERIF = {
    "full": "YES — stated as fully human-reviewed",
    "partial": "PARTLY — a stated subset/sample was human-reviewed",
    "per_item_flags": "PER-ITEM — the dataset ships per-item human-check flags",
    "none": "NO — creators' own account describes an automated-only pipeline",
    "not_applicable": "N/A — native original (no translation to verify)",
    "unknown": "UNKNOWN — no public statement found",
}


def _render_record(rec: dict, records_by_dataset: dict[str, list[dict]]) -> str:
    lines: list[str] = []
    ds = rec["dataset"]
    ev_by_id = {e["id"]: e for e in rec["evidence"]}

    def cite(dim: str) -> str:
        claim = rec["claims"][dim]
        refs = ",".join(claim["evidence"]) or "-"
        return f"[{claim['status']}; evidence {refs}]"

    title = ds["id"] + (f" (config: {ds['config']})" if ds.get("config") else "")
    lines.append(title)
    lines.append(f"  record        {rec['record_id']}  (schema {rec['schema_version']})")
    lines.append(f"  hub           {ds['hub']}  {ds['url']}")
    lines.append(f"  revision      {ds['revision']}")
    lines.append(f"  family        {rec['root_benchmark']}")
    df = rec["derived_from"]
    parent_txt = df["parent_id"] if df["parent_id"] else "-"
    lines.append(f"  derivation    {df['kind']}  parent: {parent_txt}  {cite('derived_from')}")
    langs = ", ".join(rec["target_languages"])
    src = rec["source_language"]
    lines.append(f"  languages     {langs}" + (f"  (from {src})" if src not in ("not_applicable",) else ""))
    lines.append("")
    lines.append(f"  Machine translated?   {_YESNO[rec['translation_type']]}  {cite('translation_type')}")
    eng = rec["engine_or_translator"]
    if eng not in ("unknown", "not_applicable"):
        lines.append(f"  Engine / translator   {eng}  {cite('engine_or_translator')}")
    else:
        lines.append(f"  Engine / translator   {eng.upper()}  {cite('engine_or_translator')}")
    lines.append(f"  Human verified?       {_VERIF[rec['human_verification']]}  {cite('human_verification')}")
    if rec.get("per_item_provenance"):
        pip = rec["per_item_provenance"]
        lines.append(f"    per-item field:     '{pip['field']}'" + (f" — {pip['description']}" if pip.get("description") else ""))
    lines.append(f"  License (declared)    {rec['license']}  {cite('license')}")

    # upstream walk (one step)
    if df["parent_id"]:
        parents = records_by_dataset.get(df["parent_id"], [])
        if parents:
            p = parents[0]
            lines.append(f"  Upstream step         {df['parent_id']}: {p['translation_type']}"
                         + (f" ({p['engine_or_translator']})" if p["engine_or_translator"] not in ("unknown", "not_applicable") else "")
                         + f" — see record {p['record_id']}")
        else:
            lines.append(f"  Upstream step         {df['parent_id']}: not in registry")

    unknowns = unknown_dimensions(rec)
    lines.append("")
    lines.append(f"  Provenance state      {rec['provenance_state'].upper()}  "
                 f"(completeness {rec['completeness']:.2f})")
    lines.append(f"  Unknown dimensions    {', '.join(unknowns) if unknowns else 'none'}")

    conflicts = [(d, rec["claims"][d]["conflicts"]) for d in CORE_DIMS if rec["claims"][d].get("conflicts")]
    for dim, confs in conflicts:
        lines.append(f"  CONFLICT in {dim}:")
        primary = {"derived_from": rec["derived_from"]["kind"]}.get(dim, rec.get(dim))
        lines.append(f"    primary: {primary!r}  (evidence {','.join(rec['claims'][dim]['evidence']) or '-'})")
        for c in confs:
            lines.append(f"    also attested: {c['value']!r}  (evidence {','.join(c['evidence'])})"
                         + (f" — {c['note']}" if c.get("note") else ""))

    lines.append("")
    lines.append("  Evidence:")
    for e in rec["evidence"]:
        pin = f" @ {e['hub_revision'][:12]}" if e.get("hub_revision") else ""
        lines.append(f"    {e['id']}  {e['type']:14s} {e['url']}{pin}  (retrieved {e['retrieved']})")
        if e.get("quote"):
            lines.append(f"        \"{e['quote']}\"")
        if e.get("note"):
            lines.append(f"        note: {e['note']}")
    if rec.get("notes"):
        lines.append(f"  Notes: {rec['notes']}")
    lines.append(f"  Curated {rec['curated']['date']} by {rec['curated']['by']} ({rec['curated']['method']})")
    return "\n".join(lines)


def cmd_inspect(args: argparse.Namespace) -> int:
    records, _, err = _load_registry_records(args)
    if err is not None:
        return err
    assert records is not None
    matches = _match_records(records, args.query)
    if not matches:
        print(f"no record matches '{args.query}'", file=sys.stderr)
        return 1
    if args.json:
        print(json.dumps(matches if len(matches) > 1 else matches[0], indent=2, ensure_ascii=False))
        return 0
    if len(matches) > 8:
        print(f"{len(matches)} records match '{args.query}'; showing ids only "
              f"(re-run with an exact record id):")
        for r in matches:
            print(f"  {r['record_id']}")
        return 0
    by_dataset: dict[str, list[dict]] = {}
    for r in records:
        by_dataset.setdefault(r["dataset"]["id"], []).append(r)
    print("\n\n".join(_render_record(r, by_dataset) for r in matches))
    return 0


# ------------------------------------------------------------------ stats

def cmd_stats(args: argparse.Namespace) -> int:
    records, reg_path, err = _load_registry_records(args)
    if err is not None:
        return err
    assert records is not None and reg_path is not None
    s = registry_stats(records)
    if args.json:
        print(json.dumps(s, indent=2, ensure_ascii=False))
        return 0

    def block(title: str, d: dict) -> None:
        print(f"\n{title}")
        for k, v in d.items():
            print(f"  {k:32s} {v}")

    print(f"registry: {reg_path}")
    print(f"records: {s['records']}   datasets: {s['datasets']}   languages: {s['languages']}")
    block("by translation_type", s["by_translation_type"])
    block("by human_verification", s["by_human_verification"])
    block("by provenance_state", s["by_provenance_state"])
    block("by family", s["by_family"])
    block("top languages", s["top_languages"])
    block("top engines / translators", s["top_engines_or_translators"])
    block("unknown-by-dimension (count of records)", s["unknown_by_dimension"])
    c = s["completeness"]
    print(f"\ncompleteness: mean {c['mean']}  median {c['median']}  min {c['min']}  max {c['max']}")
    print(f"records with any name_only claim: {s['records_with_name_only_claims']}")
    print(f"records with revision-pinned evidence: {s['records_with_pinned_evidence']}")
    print(f"curation method: {s['by_curation_method']}")
    return 0


# ------------------------------------------------------------------ build

def cmd_build(args: argparse.Namespace) -> int:
    root = find_repo_root()
    if root is None:
        return _fail("no benchprov data root found (set BENCHPROV_ROOT or run inside the repository)")
    report, changed = build(root, check_only=args.check)
    _print_report(report, args.json)
    if not report.ok:
        return 1
    if args.check:
        print("registry is up to date with sources")
        return 0
    print("registry rebuilt (changed)" if changed else "registry unchanged")
    return 0


# ------------------------------------------------------------------ main

def main(argv: list[str] | None = None) -> int:
    # Records are UTF-8 (language names, quotes in many scripts); keep output
    # legible on Windows consoles that default to a legacy code page.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8", errors="replace")
            except (OSError, ValueError):  # pragma: no cover
                pass
    parser = argparse.ArgumentParser(
        prog="benchprov",
        description="Benchmark Translation Provenance — inspect, validate, and summarize "
                    "evidence-backed provenance records for multilingual/translated NLP benchmarks.",
    )
    parser.add_argument("--version", action="version", version=f"benchprov {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    p_inspect = sub.add_parser("inspect", help="show the provenance card for a record or dataset")
    p_inspect.add_argument("query", help="record_id, dataset id, or substring")
    p_inspect.add_argument("--registry", help="path to a provenance.jsonl (default: repository registry)")
    p_inspect.add_argument("--json", action="store_true", help="machine-readable output")
    p_inspect.set_defaults(func=cmd_inspect)

    p_validate = sub.add_parser("validate", help="validate records (file, dir, or .jsonl); "
                                                 "with no path: validate the repository sources + registry")
    p_validate.add_argument("path", nargs="?", help="record .json, directory of records, or registry .jsonl")
    p_validate.add_argument("--json", action="store_true", help="machine-readable output")
    p_validate.set_defaults(func=cmd_validate)

    p_stats = sub.add_parser("stats", help="registry summary statistics")
    p_stats.add_argument("--registry", help="path to a provenance.jsonl (default: repository registry)")
    p_stats.add_argument("--json", action="store_true", help="machine-readable output")
    p_stats.set_defaults(func=cmd_stats)

    p_build = sub.add_parser("build", help="rebuild registry/provenance.jsonl from sources/records/")
    p_build.add_argument("--check", action="store_true",
                         help="verify the committed registry matches a rebuild (no writes)")
    p_build.add_argument("--json", action="store_true", help="machine-readable output")
    p_build.set_defaults(func=cmd_build)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except (OSError, json.JSONDecodeError) as exc:
        return _fail(str(exc))


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
