# Batch 2 — machine/LLM-translated benchmark variants (mostly MMLU family).
# Curator judgments (2026-08-24) over pinned snapshots + cited papers/repos.
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from make_records import load_snapshot, write_records  # noqa: E402


def yaml_langs(ds, drop=("en", "code")):
    langs = load_snapshot(ds)["hub_metadata"]["cardData_language"] or []
    if isinstance(langs, str):
        langs = [langs]
    return [l for l in langs if l not in drop]


def fi(lang_name, lang_code):
    """FreedomIntelligence MMLU_<Language> — identical one-line cards."""
    ds = f"FreedomIntelligence/MMLU_{lang_name}"
    return dict(
        ds=ds, family="MMLU", langs=[lang_code],
        kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
        parent_url="https://huggingface.co/datasets/cais/mmlu",
        tt="machine", engine="gpt-3.5-turbo", engine_ev=["card"],
        tt_ev=["card"],
        card_quote=f"{lang_name} version of MMLU dataset tranlasted by gpt-3.5-turbo.",
        card_note="sic — 'tranlasted' as written in the card",
        verif="unknown",
        verif_note="no statement about human review in the card at the pinned revision",
        kind_ev=["card"], license="mit", license_ev=["meta"],
        notes="Part of the MultilingualSIFT project's per-language MMLU translations.",
    )


MLMM_QUOTE = ("These datasets are translated from the original ARC, HellaSwag, and MMLU "
              "datasets in English using ChatGPT.")

SPECS = [
    fi("Arabic", "ar"),
    fi("Japanese", "ja"),
    fi("Indonesian", "id"),
    fi("Korean", "ko"),
    fi("Spanish", "es"),

    dict(ds="jon-tow/okapi_mmlu", family="MMLU", langs=yaml_langs("jon-tow/okapi_mmlu"),
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", engine="ChatGPT (gpt-3.5 class, per Okapi/mlmm project docs)",
         tt_ev=["card", "content"], engine_ev=["content"],
         card_quote="Multilingual translation of Measuring Massive Multitask Language Understanding (MMLU).",
         content_url="https://github.com/nlp-uoregon/mlmm-evaluation/blob/main/README.md",
         content_quote=MLMM_QUOTE,
         content_note="the Okapi/mlmm-evaluation repository documents the translation of these datasets",
         verif="unknown",
         verif_note="no human-review statement found in card or project README",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"],
         notes="Okapi (University of Oregon) translations, 26+ languages; widely consumed via lm-evaluation-harness 'okapi' tasks, which carry a 'Machine Translated' notice."),
    dict(ds="jon-tow/okapi_truthfulqa", family="TruthfulQA", langs=yaml_langs("jon-tow/okapi_truthfulqa"),
         kind="translation_of", parent="truthfulqa/truthful_qa", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/truthfulqa/truthful_qa",
         tt="unknown", engine="unknown",
         tt_note="the card states only 'Multilingual translation of TruthfulQA'; the Okapi/mlmm README documents ChatGPT translation for ARC/HellaSwag/MMLU but makes no equivalent statement for TruthfulQA",
         engine_note="not stated for this set; cf. alexandrainst/m_truthfulqa, which attributes its University-of-Oregon TruthfulQA translations to GPT-3.5-turbo",
         verif="unknown",
         verif_note="no statement found",
         kind_ev=["card"], card_quote="Multilingual translation of TruthfulQA.",
         license="cc-by-nc-4.0", license_ev=["meta"]),

    # ---- alexandrainst re-hosts with per-language engines: split records ----
    dict(ds="alexandrainst/m_mmlu", config=None, family="MMLU",
         langs=[l for l in yaml_langs("alexandrainst/m_mmlu") if l not in ("is", "nb", "no")],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", engine="gpt-3.5-turbo (University of Oregon translations)",
         tt_ev=["card"], engine_ev=["card"],
         card_quote="The rest of the languages was translated using GPT-3.5-turb[o] by the University of Oregon",
         card_note="record covers all languages except is/nb, which have their own records",
         verif="unknown", verif_note="no human-review statement in the card",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"]),
    dict(ds="alexandrainst/m_mmlu", config="is", family="MMLU", langs=["is"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", engine="Miðeind Greynir model", tt_ev=["card"], engine_ev=["card"],
         card_quote="The Icelandic (is) part was translated with Miðeind's Greynir model",
         verif="unknown", verif_note="no human-review statement in the card",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"]),
    dict(ds="alexandrainst/m_mmlu", config="nb", family="MMLU", langs=["nb"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", engine="DeepL", tt_ev=["card"], engine_ev=["card"],
         card_quote="Norwegian (nb) was translated with DeepL",
         verif="unknown", verif_note="no human-review statement in the card",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"]),
    dict(ds="alexandrainst/m_truthfulqa", family="TruthfulQA",
         langs=yaml_langs("alexandrainst/m_truthfulqa"),
         kind="translation_of", parent="truthfulqa/truthful_qa", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/truthfulqa/truthful_qa",
         tt="machine", engine="gpt-3.5-turbo (University of Oregon translations)",
         tt_ev=["card"], engine_ev=["card"],
         card_quote="This dataset is a machine translated version of the TruthfulQA dataset, translated using GPT-3.5-turbo.",
         verif="unknown", verif_note="no human-review statement in the card",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"]),
    dict(ds="alexandrainst/m_hellaswag", config=None, family="HellaSwag",
         langs=[l for l in yaml_langs("alexandrainst/m_hellaswag") if l not in ("is", "nb", "no")],
         kind="translation_of", parent="Rowan/hellaswag", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/Rowan/hellaswag",
         tt="machine", engine="gpt-3.5-turbo (University of Oregon translations)",
         tt_ev=["card"], engine_ev=["card"],
         card_quote="The rest of the languages was translated using GPT-3.5-turbo by the University of Oregon",
         card_note="record covers all languages except is/nb, which have their own records",
         verif="unknown", verif_note="no human-review statement in the card",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"]),
    dict(ds="alexandrainst/m_hellaswag", config="is", family="HellaSwag", langs=["is"],
         kind="translation_of", parent="Rowan/hellaswag", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/Rowan/hellaswag",
         tt="machine", engine="Miðeind Greynir model", tt_ev=["card"], engine_ev=["card"],
         card_quote="The Icelandic (is) part was translated with Miðeind's Greynir model",
         verif="unknown", verif_note="no human-review statement in the card",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"]),
    dict(ds="alexandrainst/m_hellaswag", config="nb", family="HellaSwag", langs=["nb"],
         kind="translation_of", parent="Rowan/hellaswag", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/Rowan/hellaswag",
         tt="machine", engine="DeepL", tt_ev=["card"], engine_ev=["card"],
         card_quote="Norwegian (nb) was translated with DeepL",
         verif="unknown", verif_note="no human-review statement in the card",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"]),

    dict(ds="mesolitica/translated-MMLU", family="MMLU", langs=["ms"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", engine="Google Translate", tt_ev=["card"], engine_ev=["card"],
         card_quote="Originally from https://huggingface.co/datasets/cais/mmlu, translated to Malay using Google Translate.",
         verif="none", verif_ev=["card2"],
         card2_quote="We found out some translated answers not really coherent with original English answers, so it is better to skip translated answers.",
         card2_note="creators acknowledge unfixed translation issues and recommend skipping translated answers — no correction pass applied",
         verif_note="the card's own account flags known issues left uncorrected; no review/QA step described",
         kind_ev=["card"], license="unknown",
         license_note="no license declared in hub metadata at the pinned revision"),
    dict(ds="NLPCoreTeam/mmlu_ru", family="MMLU", langs=["ru"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", engine="Yandex.Translate API", tt_ev=["card"], engine_ev=["card"],
         card_quote="The translation was made via Yandex.Translate API.",
         verif="none", verif_ev=["card2"],
         card2_quote="There are some translation mistakes, especially observed with terms and formulas, no fixes were applied.",
         verif_note="creators acknowledge mistakes and state no fixes were applied; no systematic verification described",
         kind_ev=["card"], license="unknown",
         license_note="no license declared in hub metadata at the pinned revision",
         notes="Ships ru and en columns; this record covers the Russian translation."),
    dict(ds="malhajar/mmlu_tr-v0.2", family="MMLU", langs=["tr"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", engine="GPT-4", tt_ev=["card"], engine_ev=["card"],
         card_quote="The dataset was curated by Mohamad Alhajar, leveraging GPT-4 for translations to ensure high linguistic quality and fidelity.",
         verif="unknown", verif_note="no human-review statement in the card",
         kind_ev=["card"], license="apache-2.0", license_ev=["meta"],
         notes="Built for the OpenLLMTurkishLeaderboard v0.2."),
    dict(ds="efederici/MMLU-Pro-ita", family="MMLU-Pro", langs=["it"],
         kind="translation_of", parent="TIGER-Lab/MMLU-Pro", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/TIGER-Lab/MMLU-Pro",
         tt="machine", engine="Claude Opus (draft-and-refine)", tt_ev=["card"], engine_ev=["card"],
         card_quote="The dataset was translated using Claude Opus using a *draft and refine* technique. Only the refined translation was kept.",
         verif="unknown",
         verif_note="draft-and-refine is a model-side technique; no human review stated",
         kind_ev=["card"], license="mit", license_ev=["meta"]),
    dict(ds="bezir/MMLU-pro-TR", family="MMLU-Pro", langs=["tr"],
         kind="translation_of", parent="TIGER-Lab/MMLU-Pro", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/TIGER-Lab/MMLU-Pro",
         tt="machine", engine="Gemini-1.5-Pro", tt_ev=["card"], engine_ev=["card"],
         card_quote="this dataset was translated with ```human oversight``` and the assistance of ```Gemini-1.5-pro```",
         verif="partial", verif_ev=["card"],
         verif_note="'human oversight' is stated but its scope/coverage is not quantified",
         kind_ev=["card"], license="mit", license_ev=["meta"]),
    dict(ds="richmondsin/m_mmlu", family="MMLU", langs=yaml_langs("richmondsin/m_mmlu"),
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", engine="gpt-3.5-turbo (University of Oregon translations)",
         tt_ev=["card"], engine_ev=["card"],
         card_quote="The languages was translated using GPT-3.5-turbo by the University of Oregon, and this part of the dataset was originally uploaded to [the mlmm-evaluation] Github repository.",
         verif="unknown", verif_note="no human-review statement in the card",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"],
         notes="Partial re-host of the Okapi/mlmm translations."),
    dict(ds="sarvamai/mmlu-indic", family="MMLU", langs=yaml_langs("sarvamai/mmlu-indic"),
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="unknown", engine="unknown",
         tt_note="the card confirms translation ('translated from English into 10 Indian languages') but states no method (machine vs human) at the pinned revision",
         engine_note="no engine or translating party named",
         verif="unknown", verif_note="no statement",
         kind_ev=["card"],
         card_quote="A multilingual version of the Massive Multitask Language Understanding (MMLU) benchmark, translated from English into 10 Indian languages.",
         license="mit", license_ev=["meta"]),
    dict(ds="Institute-Disease-Modeling/mmlu-winogrande-afr", family="MMLU",
         langs=yaml_langs("Institute-Disease-Modeling/mmlu-winogrande-afr"),
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="human", engine="human translators (per paper arXiv:2412.12417)",
         tt_ev=["card"], engine_ev=["card"],
         card_quote="This HuggingFace Dataset contains the human-translated benchmarks we created from our paper",
         verif="unknown", verif_note="translation is human; a separate verification step is not described in the card",
         kind_ev=["card"], license="mit", license_ev=["meta"],
         notes="Human-translated MMLU (and Winogrande) into African languages; this record covers the MMLU portion hosted here — the repo bundles both benchmarks."),
    dict(ds="openGPT-X/mmlux", family="MMLU", langs=yaml_langs("openGPT-X/mmlux"),
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["paper"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", engine="DeepL", tt_ev=["paper"], engine_ev=["paper"],
         paper_url="https://arxiv.org/html/2410.08928",
         paper_quote="3.1 Translation Process We chose DeepL as translation service due to its balance between translation accuracy and scalability. We translated five well-known datasets, ARC [et al.]",
         paper_note="paper cited in the dataset card's citation block (Thellmann et al., 2024)",
         verif="unknown", verif_note="no human-review statement found in card or paper section retrieved",
         kind_ev=["paper"], license="unknown",
         license_note="no license declared in hub metadata at the pinned revision; card tags contradict each other ('synthetic' tag vs 'language_creators: expert-generated')",
         notes="EU-language MMLU translations (MMLUX) from the openGPT-X evaluation effort."),
    dict(ds="LumiOpen/opengpt-x_mmlux", family="MMLU", langs=yaml_langs("LumiOpen/opengpt-x_mmlux"),
         kind="subset_or_filter_of", parent="openGPT-X/mmlux",
         parent_url="https://huggingface.co/datasets/openGPT-X/mmlux",
         tt="machine", engine="DeepL",
         tt_ev=["card", "paper"], engine_ev=["paper"],
         card_quote="This is a copy of the translations from openGPT-X/mmlux, but the repo is [modified so it doesn't require trusting remote code]",
         paper_url="https://arxiv.org/html/2410.08928",
         paper_quote="We chose DeepL as translation service due to its balance between translation accuracy and scalability.",
         paper_note="method of the parent's translations, documented in the openGPT-X evaluation paper",
         verif="unknown", verif_note="no human-review statement found",
         kind_ev=["card"], license="unknown",
         license_note="no license declared in hub metadata at the pinned revision",
         notes="Re-host (loader-safe copy) of openGPT-X/mmlux; items unchanged per card."),
    dict(ds="fair-forward/mmlu-autotranslated", family="MMLU", langs=["mul"],
         kind="translation_of", parent="cais/mmlu", src="unknown",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", tt_ev=["name"], engine="unknown",
         name_note="dataset id contains 'autotranslated'; the card is YAML-only with no prose at the pinned revision",
         tt_note="method class rests on the dataset's own name only",
         engine_note="no engine stated anywhere in the repo card",
         src_note="source language not stated; per-language configs named by language code",
         verif="unknown", verif_note="no statement",
         kind_ev=["name"], kind_note="MMLU identity from the dataset name and per-subject structure; no prose statement",
         license="unknown", license_note="no license declared in hub metadata",
         notes="Auto-translated MMLU used by the AI Language Proficiency Monitor (GIZ FAIR Forward); the repo itself documents nothing — a showcase 'name_only' row."),
    dict(ds="allganize/financial-mmlu-ko", family="MMLU", langs=["ko"],
         kind="modeled_on", parent="cais/mmlu",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="mixed", engine="GPT-4 (generated portion)",
         tt_ev=["card"], engine_ev=["card"],
         card_quote="한국어 데이터를 생성하기 위해, 여러 금융 문제가 있는 공공 사이트의 문제들을 크롤링하여 수집, 검수(104건)하였습니다. 그리고 Wikipedia와 공공사이트들의 금융사전/보고서들을 기반으로 GPT-4로 문제를 생성하고 사람이 검수하였습니다.(315건)",
         card_note="Korean: 104 items collected from public sites and reviewed; 315 items generated with GPT-4 from Wikipedia/financial references and human-reviewed",
         verif="full", verif_ev=["card"],
         verif_note="both portions described as human-reviewed (검수)",
         kind_ev=["card"], license="unknown",
         license_note="no license declared in hub metadata at the pinned revision",
         notes="NOT a translation: natively collected + LM-generated Korean financial MC items in MMLU style."),
]

if __name__ == "__main__":
    written = write_records(SPECS)
    print(f"batch 2: {len(written)} records")
