# Batch 1 — family anchors and major multilingual sets.
# Curator judgments (2026-08-19) over pinned evidence snapshots + cited papers.
# Run: python tools/curation/seed_batch_1_anchors.py
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from make_records import ROOT, load_snapshot, write_records  # noqa: E402


def yaml_langs(ds, drop=("en", "code")):
    langs = load_snapshot(ds)["hub_metadata"]["cardData_language"] or []
    if isinstance(langs, str):
        langs = [langs]
    out = [l for l in langs if l not in drop]
    return out


SPECS = [
    # ---------------- originals (family roots, native) ----------------
    dict(ds="cais/mmlu", family="MMLU", langs=["en"], kind="none", parent=None,
         tt="native_original",
         tt_ev=["meta_tags"], meta_tags_quote="source_datasets: original; language: en; annotations_creators: no-annotation",
         meta_tags_note="hub metadata declares the dataset original English",
         kind_ev=["meta_tags"], license="mit", license_ev=["meta"],
         notes="Family root. Questions collected from freely available online sources by the authors (Hendrycks et al., 2021)."),
    dict(ds="openai/gsm8k", family="GSM8K", langs=["en"], kind="none", parent=None,
         tt="native_original",
         tt_ev=["meta_tags"], meta_tags_quote="source_datasets: original; language: en; annotations_creators: crowdsourced",
         kind_ev=["meta_tags"], license="mit", license_ev=["meta"],
         notes="Family root; problems written by human problem writers (Cobbe et al., 2021)."),
    dict(ds="allenai/ai2_arc", family="ARC", langs=["en"], kind="none", parent=None,
         tt="native_original",
         tt_ev=["meta_tags"], meta_tags_quote="source_datasets: original; language: en; annotations_creators: found",
         kind_ev=["meta_tags"], license="cc-by-sa-4.0", license_ev=["meta"],
         notes="Family root; natural grade-school science questions."),
    dict(ds="Rowan/hellaswag", family="HellaSwag", langs=["en"], kind="none", parent=None,
         tt="native_original",
         tt_ev=["card"], card_quote="HellaSwag: Can a Machine Really Finish Your Sentence? is a new dataset for commonsense NLI.",
         card_note="original English dataset (Zellers et al., 2019); contexts from ActivityNet/WikiHow with adversarially filtered machine-written negatives",
         kind_ev=["card"], license="unknown",
         license_note="no license declared in hub metadata or card at the pinned revision",
         notes="Family root. The license dimension is 'unknown' because the HF repo declares none."),
    dict(ds="truthfulqa/truthful_qa", family="TruthfulQA", langs=["en"], kind="none", parent=None,
         tt="native_original",
         tt_ev=["card"], card_quote="We constructed the questions using the following adversarial procedure, with GPT-3-175B (QA prompt) as the target model: 1. We wrote questions that some humans would answer falsely.",
         kind_ev=["card"], license="apache-2.0", license_ev=["meta"],
         notes="Family root; questions written by the authors."),
    dict(ds="allenai/winogrande", family="Winogrande", langs=["en"], kind="none", parent=None,
         tt="native_original",
         tt_ev=["meta_tags"], meta_tags_quote="language: en (hub metadata); crowdsourced Winograd-schema-style problems",
         meta_tags_note="card carries no creation prose at pinned revision; identity from hub metadata and the WinoGrande paper (Sakaguchi et al., 2020)",
         kind_ev=["meta_tags"], license="unknown",
         license_note="no license declared in hub metadata at the pinned revision"),
    dict(ds="rajpurkar/squad", family="SQuAD", langs=["en"], kind="none", parent=None,
         tt="native_original",
         tt_ev=["card"], card_quote="consisting of questions posed by crowdworkers on a set of Wikipedia articles",
         kind_ev=["card"], license="cc-by-sa-4.0", license_ev=["meta"]),
    dict(ds="allenai/openbookqa", family="OpenBookQA", langs=["en"], kind="none", parent=None,
         tt="native_original",
         tt_ev=["meta_tags"], meta_tags_quote="source_datasets: original; annotations_creators: crowdsourced, expert-generated",
         kind_ev=["meta_tags"], license="unknown",
         license_note="hub metadata license tag is 'unknown'"),
    dict(ds="ybisk/piqa", family="PIQA", langs=["en"], kind="none", parent=None,
         tt="native_original",
         tt_ev=["card"], card_quote="Annotations are by construction obtained when crowdsourcers complete the prompt.",
         kind_ev=["meta_tags"], meta_tags_quote="source_datasets: original", license="unknown",
         license_note="hub metadata license tag is 'unknown'"),
    dict(ds="tau/commonsense_qa", family="CommonsenseQA", langs=["en"], kind="none", parent=None,
         tt="native_original",
         tt_ev=["meta_tags"], meta_tags_quote="source_datasets: original; annotations_creators: crowdsourced",
         kind_ev=["meta_tags"], license="mit", license_ev=["meta"]),
    dict(ds="google/boolq", family="BoolQ", langs=["en"], kind="none", parent=None,
         tt="native_original",
         tt_ev=["card"], card_quote="occurring ---they are generated in unprompted and unconstrained settings.",
         card_note="questions are naturally occurring search queries (Clark et al., 2019)",
         kind_ev=["meta_tags"], meta_tags_quote="source_datasets: original", license="cc-by-sa-3.0", license_ev=["meta"]),
    dict(ds="google-research-datasets/tydiqa", family="TyDiQA", langs=yaml_langs("google-research-datasets/tydiqa"),
         kind="none", parent=None,
         tt="native_original",
         tt_ev=["card"], card_quote="the data is collected directly in each language without the use of translation (unlike MLQA and XQuAD).",
         kind_ev=["card"], license="apache-2.0", license_ev=["meta"],
         notes="Native multilingual contrast row: 11 typologically diverse languages, questions written natively."),
    dict(ds="tatsu-lab/alpaca", family="Alpaca", langs=["en"], kind="none", parent=None,
         tt="lm_generated", engine="OpenAI text-davinci-003", engine_ev=["card"],
         tt_ev=["card"], card_quote="Alpaca is a dataset of 52,000 instructions and demonstrations generated by OpenAI's `text-davinci-003` engine.",
         verif="unknown",
         verif_note="no statement about human review of generated instances found in the card at the pinned revision",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"],
         notes="Family root for translated Alpaca variants; itself LM-generated English."),
    dict(ds="TIGER-Lab/MMLU-Pro", family="MMLU-Pro", langs=["en"], kind="aggregation_of", parent="cais/mmlu",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="native_original",
         tt_ev=["paper"], paper_url="https://arxiv.org/abs/2406.01574",
         paper_quote="integrating more challenging, reasoning-focused questions and expanding the choice set from four to ten options",
         paper_note="English items drawn from MMLU plus newly collected questions; no translation involved",
         kind_ev=["paper"], license="mit", license_ev=["meta"],
         notes="Aggregates filtered MMLU items with newly collected English questions (TheoremQA, SciBench, STEM sources per paper)."),

    # ---------------- re-annotated / revised English subsets ----------------
    dict(ds="edinburgh-dawg/mmlu-redux", family="MMLU-Redux", langs=["en"],
         kind="subset_or_filter_of", parent="cais/mmlu",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="native_original",
         tt_ev=["card"], card_quote="MMLU-Redux is a subset of 3,000 manually re-annotated questions across 30 MMLU subjects.",
         kind_ev=["card"], license="cc-by-4.0", license_ev=["meta"],
         per_item=dict(field="error_type",
                       description="per-item error annotation: ok / bad_question_clarity / bad_options_clarity / no_correct_answer / multiple_correct_answers / wrong_groundtruth"),
         notes="English re-annotation row (label QA, not translation); consumed by lm-evaluation-harness to exclude non-'ok' items."),
    dict(ds="madrylab/gsm8k-platinum", family="GSM8K", langs=["en"],
         kind="subset_or_filter_of", parent="openai/gsm8k",
         parent_url="https://huggingface.co/datasets/openai/gsm8k",
         tt="native_original",
         tt_ev=["card"], card_quote="1. *consensus*: all LLMs agreed with the label, so the example was not manually reviewed. 2. *verified*: the original target was manually verified to be correct.",
         card_note="revised GSM8K test set: items flagged by LLMs, then manually verified/re-labeled or rejected",
         kind_ev=["card"], license="mit", license_ev=["meta"],
         per_item=dict(field="cleaning_status",
                       description="per-item label-verification status (consensus / verified / re-labeled)"),
         notes="English label-revision row; 'The further annotations we provide are licensed under the CC BY-SA 4.0 license' per card — hub license tag records mit."),

    # ---------------- professionally human-translated multilingual sets ----------------
    dict(ds="openai/MMMLU", family="MMLU", langs=yaml_langs("openai/MMMLU"),
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="human", engine="professional human translators (unnamed vendor)", engine_ev=["card"],
         verif="unknown",
         verif_note="card states professional human translation; no separate post-translation QA/verification step is described at the pinned revision",
         tt_ev=["card"], card_quote="We translated the MMLU's test set into 14 languages using professional human translators.",
         kind_ev=["card"], license="mit", license_ev=["meta"]),
    dict(ds="juletxara/mgsm", family="MGSM", langs=yaml_langs("juletxara/mgsm"),
         kind="translation_of", parent="openai/gsm8k", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/openai/gsm8k",
         tt="human", engine="human annotators (Shi et al., 2022)", engine_ev=["card"],
         verif="unknown",
         verif_note="human-translated by construction; no separate verification step described in the card",
         tt_ev=["card"], card_quote="The same 250 problems from GSM8K are each translated via human annotators in 10 languages.",
         kind_ev=["card"], license="cc-by-sa-4.0", license_ev=["meta"],
         notes="MGSM is itself the family origin record for translated-GSM8K evaluation; exemplars also manually translated."),
    dict(ds="google/xquad", family="SQuAD", langs=yaml_langs("google/xquad"),
         kind="translation_of", parent="rajpurkar/squad", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/rajpurkar/squad",
         tt="human", engine="professional translators (unnamed)", engine_ev=["card", "paper"],
         verif="unknown",
         verif_note="professional translation stated; no separate verification step described",
         tt_ev=["card", "paper"],
         card_quote="of SQuAD v1.1 (Rajpurkar et al., 2016) together with their professional translations into ten languages",
         paper_url="https://arxiv.org/abs/1910.11856",
         paper_quote="1190 question-answer pairs from SQuAD v1.1 translated into ten languages by professional translators",
         kind_ev=["card"], license="cc-by-sa-4.0", license_ev=["meta"]),
    dict(ds="facebook/belebele", family="Belebele", langs=["mul"],
         kind="translation_of", parent="facebook/flores", src="en", src_ev=["paper"],
         parent_url="https://huggingface.co/datasets/facebook/flores",
         tt="human", engine="Language Service Provider (professional, unnamed)", engine_ev=["paper"],
         verif="full", verif_ev=["paper"],
         tt_ev=["paper"],
         paper_url="https://arxiv.org/html/2308.16884",
         paper_quote="We opted to create multiple-choice questions and answers in English and then translate",
         paper_note="'We implement an iterative procedure with the Language Service Provider (LSP)'; 'extensive quality-assurance loops implemented by the NLLB team and the LSP'",
         verif_note="iterative QA loops with the LSP described in the paper",
         kind_ev=["paper"], license="cc-by-sa-4.0", license_ev=["meta"],
         notes="122 language variants; passages are FLORES-200 sentences (themselves professionally translated); target_languages recorded as 'mul' — see the dataset for the full variant list."),
    dict(ds="openlanguagedata/flores_plus", family="FLORES", langs=["mul"],
         kind="translation_of", parent="facebook/flores", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/facebook/flores",
         tt="human", engine="unknown",
         engine_note="human translation program (FLORES-200 lineage, OLDI-maintained); translating parties not named in the card",
         verif="unknown",
         verif_note="FLORES workflow includes review per external documentation; not stated in the card at the pinned revision",
         tt_ev=["card"],
         card_quote="The data consists of translations primarily from English into over 200 language varieties.",
         card_note="'FLORES+ is based on FLORES-200'; OLDI contribution guidelines require human translation",
         kind_ev=["card"], license="cc-by-sa-4.0", license_ev=["meta"],
         notes="Gated dataset: the pinned card URL requires an authenticated, condition-accepting session."),
    dict(ds="EC-DGT-AI/EU-MMLU", family="MMLU", langs=["mul"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="human", engine="European Commission DG Translation + EMT Network translators", engine_ev=["card"],
         verif="unknown",
         verif_note="professional translation stated; a separate verification step is not described at the pinned revision",
         tt_ev=["card"],
         card_quote="The translation has been performed by experienced professional tra[nslators]",
         card2_quote="The EU-MMLU dataset is a first step, consisting in the translation of a subset of the MMLU dataset into all 24 EU official languages.",
         card_note="translators: European Commission Directorate-General for Translation and the EMT (European Master's in Translation) network",
         kind_ev=["card2"], license="mit", license_ev=["meta"],
         license_note="hub tag 'mit'; the card additionally states the translations are made available under CC BY 4.0",
         notes="Coverage is partial and growing: 'Some contents is only partially translated in the languages listed above. The remaining EU official languages will be added soon.'"),

    # ---------------- mixed-method multilingual sets ----------------
    dict(ds="CohereLabs/Global-MMLU", family="MMLU", langs=yaml_langs("CohereLabs/Global-MMLU"),
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["paper"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="mixed", tt_ev=["card"],
         card_quote="This dataset combines machine translations for MMLU questions along with professional translations and crowd-sourced post-edits.",
         engine="Google Translate API (machine-translated portion)", engine_ev=["paper"],
         paper_url="https://arxiv.org/html/2412.03304",
         paper_quote="We first translated the English MMLU dataset into 41 languages using the Google Translate API.",
         verif="per_item_flags", verif_ev=["card2"],
         card2_quote="is_annotated dtype: bool",
         card2_note="per-item boolean marks samples that received human post-editing/verification",
         per_item=dict(field="is_annotated",
                       description="True for items that were professionally translated / human post-edited; False for raw machine translations"),
         kind_ev=["card"], license="apache-2.0", license_ev=["meta"],
         notes="42 languages including English originals; the 'en' subset (original MMLU items) is excluded from target_languages of this record. Per-language human-edit coverage varies — see is_annotated."),
    dict(ds="CohereLabs/Global-MMLU-Lite", family="MMLU", langs=yaml_langs("CohereLabs/Global-MMLU-Lite"),
         kind="subset_or_filter_of", parent="CohereLabs/Global-MMLU",
         parent_url="https://huggingface.co/datasets/CohereLabs/Global-MMLU",
         tt="mixed", tt_ev=["card"],
         card_quote="All samples in Global MMLU lite are fully human translated or post edited.",
         engine="human translators / post-editors (Cohere Labs Community + professional annotators)", engine_ev=["card2"],
         card2_quote="Curated by: Professional annotators and contributors of Cohere Labs Community",
         verif="full", verif_ev=["card"],
         verif_note="every sample either human-translated or human post-edited per the card",
         kind_ev=["card"], license="apache-2.0", license_ev=["meta"],
         notes="Lite subset: 200 culturally-sensitive + 200 culturally-agnostic samples per language; items are a subset of Global-MMLU with only human-treated samples retained."),
    dict(ds="facebook/xnli", family="XNLI", langs=yaml_langs("facebook/xnli"),
         kind="translation_of", parent="nyu-mll/multi_nli", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/nyu-mll/multi_nli",
         tt="mixed", tt_ev=["card", "paper"],
         card_quote="XNLI is a subset of a few thousand examples from MNLI which has been translated",
         paper_url="https://arxiv.org/html/1809.05053",
         paper_quote="we hire translators to translate the resulting sentences into 15 languages using the One Hour Translation platform",
         paper_note="dev/test: professional human translation; the distributed train split is machine-translated MultiNLI",
         engine="One Hour Translation platform (dev/test); MT for train split (engine unnamed)", engine_ev=["paper"],
         verif="unknown",
         verif_note="no separate post-translation verification step described",
         kind_ev=["card"], license="unknown",
         license_note="no license declared in hub metadata at the pinned revision",
         notes="Split-dependent provenance: human-translated evaluation splits, machine-translated train split — recorded as one 'mixed' record because the hub dataset ships them together."),

    # ---------------- LLM-translated multilingual sets ----------------
    dict(ds="li-lab/MMLU-ProX", family="MMLU-Pro", langs=["mul"],
         kind="translation_of", parent="TIGER-Lab/MMLU-Pro", src="en", src_ev=["paper"],
         parent_url="https://huggingface.co/datasets/TIGER-Lab/MMLU-Pro",
         tt="machine", tt_ev=["card", "paper"],
         card_quote="Employing a rigorous semi-automatic translation process with expert validation",
         paper_url="https://arxiv.org/abs/2503.10497",
         paper_quote="we employ a rigorous development process that involves multiple powerful LLMs for translation, followed by expert review to ensure accurate expression, consistent terminology, and cultural relevance",
         engine="multiple LLMs (not individually named in card/abstract)", engine_ev=["paper"],
         verif="full", verif_ev=["paper"],
         verif_note="'followed by expert review' — claimed as a process step over the dataset; coverage not quantified",
         kind_ev=["paper"], license="mit", license_ev=["meta"],
         notes="29 languages per project site; target_languages recorded as 'mul'."),
]

if __name__ == "__main__":
    written = write_records(SPECS)
    print(f"batch 1: {len(written)} records")
