# Batch 3 — regional wedge: Kazakh, Russian, Bengali, Uzbek (+Arabic natives).
# Curator judgments (2026-08-24) over pinned snapshots + cited papers/pages.
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from make_records import write_records  # noqa: E402

ISSAI_NOTE = ("Published by ISSAI (Nazarbayev University), the KazLLM program's benchmark "
              "translations. The card states machine translation but names no engine — "
              "the translation method's actor is undocumented.")

def issai(ds, family, parent, langs, quote, license_id, extra_notes=""):
    return dict(
        ds=ds, family=family, langs=langs,
        kind="translation_of", parent=parent, src="en", src_ev=["card"],
        parent_url=f"https://huggingface.co/datasets/{parent}",
        tt="machine", tt_ev=["card"], card_quote=quote,
        engine="unknown",
        engine_note="no engine or translation service named in the card at the pinned revision",
        verif="unknown", verif_note="no statement about human review in the card",
        kind_ev=["card"], license=license_id, license_ev=["meta"],
        notes=(ISSAI_NOTE + (" " + extra_notes if extra_notes else "")).strip(),
    )


SPECS = [
    # ---------------- Kazakh: ISSAI (KazLLM program) ----------------
    issai("issai/MMLU_Kazakh", "MMLU", "cais/mmlu", ["kk"],
          "This is the machine-translated Kazakh version of the MMLU (Massive Multitask Language Understanding) dataset (test split).",
          "mit"),
    issai("issai/MMLU-Pro_Kazakh_Russian", "MMLU-Pro", "TIGER-Lab/MMLU-Pro", ["kk", "ru"],
          "These are the machine-translated Kazakh and Russian versions of the MMLU-Pro (Massive Multitask Language Understanding Pro) dataset (test set).",
          "mit"),
    issai("issai/GSM8k_Kazakh_Russian", "GSM8K", "openai/gsm8k", ["kk", "ru"],
          "These are the machine-translated Kazakh and Russian versions of the GSM8K (Grade School Math 8K) dataset (test set).",
          "mit"),
    issai("issai/ARC_Kazakh_Russian", "ARC", "allenai/ai2_arc", ["kk", "ru"],
          "These are the machine-translated Kazakh and Russian versions of the ARC (AI2 Reasoning Challenge) dataset (test set).",
          "cc-by-sa-4.0"),
    dict(ds="issai/MMLU_Redux_2.0_Kazakh", family="MMLU-Redux", langs=["kk"],
         kind="translation_of", parent="edinburgh-dawg/mmlu-redux-2.0", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/edinburgh-dawg/mmlu-redux-2.0",
         tt="machine", tt_ev=["card"],
         card_quote="MMLU_Redux_2.0_Kazakh is a machine-translated Kazakh version of the original MMLU-Redux 2.0 benchmark.",
         engine="unknown",
         engine_note="no engine or translation service named in the card",
         verif="unknown", verif_note="no statement about human review in the card",
         kind_ev=["card"], license="cc-by-4.0", license_ev=["meta"],
         notes=ISSAI_NOTE + " Parent is MMLU-Redux 2.0 (the re-annotated MMLU subset), not raw MMLU."),

    # ---------------- Kazakh: kz-transformers ----------------
    dict(ds="kz-transformers/mmlu-translated-kk", family="MMLU", langs=["kk"],
         kind="translation_of", parent="cais/mmlu", src="unknown",
         src_note="translation from MMLU implied by the card's citation title; source language not explicitly stated",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="unknown", engine="unknown",
         tt_note="the card's citation block calls it 'Translated MMLU Benchmark' but states no method (machine vs human)",
         engine_note="no engine or translating party named",
         verif="unknown", verif_note="no statement",
         kind_ev=["card"],
         card_quote="title = {MMLU on kazakh language: Translated MMLU Benchmark},",
         license="apache-2.0", license_ev=["meta"],
         notes="Second independent Kazakh MMLU translation (alongside ISSAI's); method undocumented."),
    dict(ds="kz-transformers/gsm8k-kk-translated", family="GSM8K", langs=["kk"],
         kind="translation_of", parent="openai/gsm8k", src="unknown",
         src_note="translation implied by the card's citation title; source language not explicitly stated",
         parent_url="https://huggingface.co/datasets/openai/gsm8k",
         tt="unknown", engine="unknown",
         tt_note="citation title 'Kazakh GSM8K: Translated Grade School Math 8K'; no method stated",
         engine_note="no engine or translating party named",
         verif="unknown", verif_note="no statement",
         kind_ev=["card"],
         card_quote="title = {Kazakh GSM8K: Translated Grade School Math 8K},",
         license="apache-2.0", license_ev=["meta"]),
    dict(ds="kz-transformers/kazakh-unified-national-testing-mc", family="Other-native", langs=["kk"],
         kind="none", parent=None,
         tt="native_original", tt_ev=["content", "meta_tags"],
         content_url="https://datasets-server.huggingface.co/first-rows?dataset=kz-transformers%2Fkazakh-unified-national-testing-mc&config=default&split=kazakh_and_literature",
         content_note="first rows show native Kazakh UNT exam questions (e.g. on the Er Töstik folk tale); subject splits: kazakh_and_literature, geography, world_history, history_of_kazakhstan, english, biology, ...",
         meta_tags_quote="splits: kazakh_and_literature (4688), geography (1718), world_history (1228), history_of_kazakhstan (3260), english (2197), biology (1536), ...",
         meta_tags_note="subject structure of Kazakhstan's Unified National Testing (UNT) exam, from the card's YAML",
         kind_ev=["content"],
         license="apache-2.0", license_ev=["meta"],
         notes="Native Kazakh exam benchmark (UNT). An 'english' subject subset (English-language school questions) exists inside the dataset; this record's language scope covers the Kazakh-language items that dominate the collection."),
    dict(ds="kz-transformers/kk-socio-cultural-bench-mc", family="Other-native", langs=["kk"],
         kind="none", parent=None,
         tt="mixed", tt_ev=["card"],
         card_quote="By combining expert-curated topics with LLM-assisted web mining, we create a diverse dataset spanning 17 culturally salient domains",
         card_note="KazBench-KK: 7,111 Kazakh cultural-knowledge MC questions; creation combines expert curation with LLM-assisted mining of Kazakh web content",
         engine="unknown",
         engine_note="the assisting LLM(s) are not named in the card",
         verif="unknown", verif_note="no verification statement in the card",
         kind_ev=["card"], license="cc-by-4.0", license_ev=["meta"],
         notes="Published at ACL 2025 Field Matters (aclanthology.org/2025.fieldmatters-1.4)."),

    # ---------------- Kazakh/Arabic natives (MBZUAI) ----------------
    dict(ds="MBZUAI/KazMMLU", family="MMLU", langs=["kk", "ru"],
         kind="modeled_on", parent="cais/mmlu",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="native_original", tt_ev=["paper", "meta_tags"],
         paper_url="https://arxiv.org/abs/2502.12829",
         paper_quote="we introduce KazMMLU, the first MMLU-style dataset specifically designed for Kazakh language. KazMMLU comprises 23,000 questions that cover various educational levels, including STEM, humanities, and social sciences, sourced from auth[entic educational materials]",
         meta_tags_quote="tags: MMLU, exams, multilingual; configs e.g. 'Biology (High School in kaz)', 'Accounting and Auditing (Professional & University in rus)'",
         kind_ev=["paper"], license="cc-by-nc-4.0", license_ev=["meta"],
         notes="Native Kazakh + Russian exam questions (not translations); the shared native benchmark of the Kazakh ecosystem."),
    dict(ds="MBZUAI/ArabicMMLU", family="MMLU", langs=["ar"],
         kind="modeled_on", parent="cais/mmlu",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="native_original", tt_ev=["card"],
         card_quote="We present ArabicMMLU, the first multi-task language understanding benchmark for Arabic language, sourced from school exams across diverse educational levels in different countries",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"],
         notes="Native Arabic exam questions; construction involved 10 Arabic native speakers per the card."),
    dict(ds="MBZUAI/human_translated_arabic_mmlu", family="MMLU", langs=["ar"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["ext"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="human", tt_ev=["ext", "name"],
         ext_url="https://github.com/huggingface/lighteval/pull/372",
         ext_quote="`arabic_mmlu_ht`: Human-translated version from MBZUAI, providing a more accurate and high-quality translation of the original work by Hendrycks et al. (2021)",
         ext_note="merged lighteval PR that renamed Arabic MMLU tasks by translation provenance; the dataset's own card is YAML-only with no prose",
         name_note="dataset id itself: 'human_translated_arabic_mmlu'",
         engine="unknown",
         engine_note="the translating team/vendor is not named in the card (which has no prose) or the cited PR",
         verif="unknown", verif_note="no statement",
         kind_ev=["ext"], license="unknown",
         license_note="no license declared in hub metadata at the pinned revision",
         notes="A case where third-party consumer evidence (a harness PR) carries the provenance fact the dataset card omits."),

    # ---------------- Russian ----------------
    dict(ds="ai-forever/MERA", family="Other-native", langs=["ru"],
         kind="aggregation_of", parent=None,
         tt="mixed", tt_ev=["card"],
         card_quote="is an analog of the English COPA dataset that was constructed as a translation of the English COPA dataset from SuperGLUE",
         card_note="the MERA suite aggregates 20+ Russian tasks; most are natively constructed, at least one (PARus) is documented as a translation — hence 'mixed' at suite level",
         engine="unknown",
         engine_note="per-task creation varies; no single engine",
         verif="unknown",
         verif_note="some tasks document Yandex.Toloka validation ('All examples from the dataset have been validated on the Yandex.Toloka platform' — stated per-task, not suite-wide)",
         kind_ev=["card"], license="mit", license_ev=["meta"],
         notes="Suite-level record; per-task records (e.g. rummlu, parus) would be finer-grained future work."),
    dict(ds="d0rj/gsm8k-ru", family="GSM8K", langs=["ru"],
         kind="translation_of", parent="openai/gsm8k", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/openai/gsm8k",
         tt="unknown", engine="unknown",
         tt_note="card and YAML confirm translation ('Translated version of gsm8k dataset into Russian.'; 'language_creators: translated') but state no method",
         engine_note="no engine named",
         verif="unknown", verif_note="no statement",
         kind_ev=["card"],
         card_quote="Translated version of gsm8k dataset into Russian.",
         license="mit", license_ev=["meta"]),

    # ---------------- Uzbek ----------------
    dict(ds="murodbek/MMLU-uz", family="MMLU", langs=["uz"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", tt_ev=["card"],
         card_quote="This dataset was automatically translated in two stages: Base translation using the `sayqalchi` model from (Tilmoch platform).",
         engine="sayqalchi model (Tilmoch platform), two-stage automatic", engine_ev=["card"],
         verif="none", verif_ev=["card2"],
         card2_quote="**Important Note:** This is a machine-translated dataset and has **not** undergone human review or correction due to the associated costs and effort.",
         verif_note="explicit creator statement of no human review — the registry's clearest 'none'",
         kind_ev=["card"], license="apache-2.0", license_ev=["meta"],
         notes="Full MMLU dev+test in Uzbek."),
    dict(ds="murodbek/MMLU-Lite-uz", family="MMLU", langs=["uz"],
         kind="translation_of", parent="CohereLabs/Global-MMLU-Lite", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/CohereLabs/Global-MMLU-Lite",
         tt="machine", tt_ev=["card"],
         card_quote="This dataset was automatically translated in two stages: Base translation using the `sayqalchi` model from (Tilmoch platform).",
         card_note="an Uzbek version of the Global-MMLU-Lite benchmark, per the card",
         engine="sayqalchi model (Tilmoch platform), two-stage automatic", engine_ev=["card"],
         verif="none", verif_ev=["card2"],
         card2_quote="**Important Note:** This is a machine-translated dataset and has **not** undergone human review or correction due to the associated costs and effort.",
         kind_ev=["card"], license="apache-2.0", license_ev=["meta"]),
    dict(ds="behbudiy/alpaca-cleaned-uz", family="Alpaca", langs=["uz"],
         kind="translation_of", parent="yahma/alpaca-cleaned", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/yahma/alpaca-cleaned",
         tt="machine", engine="Google Translate API", tt_ev=["card"], engine_ev=["card"],
         card_quote="This dataset is a translation of the yahma/alpaca-cleaned dataset into Uzbek, leveraging the Google Translate API.",
         verif="unknown", verif_note="no statement",
         kind_ev=["card"], license="unknown",
         license_note="no license declared in hub metadata at the pinned revision"),

    # ---------------- Bengali ----------------
    dict(ds="hishab/bangla-mmlu", family="MMLU", langs=["bn"],
         kind="modeled_on", parent="cais/mmlu",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="native_original", tt_ev=["card"],
         card_quote="We curated multiple-choice questions from various open-source educational websites and textbooks, inspired by the original MMLU dataset (Hendrycks et al., 2020). The dataset includes multiple-choice questions from different Bangladeshi exams",
         kind_ev=["card"], license="unknown",
         license_note="no license declared in hub metadata at the pinned revision",
         notes="Native Bangla exam questions (116,503 items: university admission, higher secondary, job exams, medical/engineering admission)."),
    dict(ds="hishab/titulm-bangla-mmlu", family="MMLU", langs=["bn"],
         kind="unknown", parent=None,
         tt="unknown", tt_ev=["card"], engine="unknown", engine_ev=["card"],
         card_quote="Read the paper for details: https://arxiv.org/abs/2502.11187",
         card_note="the card's entire prose is this paper pointer plus a citation block; no creation statements",
         tt_note="creation method not stated in the card (evidence documents the checked card)",
         engine_note="not stated in the card",
         verif="unknown", verif_ev=["card"], verif_note="not stated in the card",
         kind_ev=["card"],
         kind_note="relationship to hishab/bangla-mmlu or other sources not stated in the card",
         license="unknown",
         license_note="no license declared in hub metadata at the pinned revision",
         notes="Pointer-only card; the TituLLMs paper likely documents creation, but the dataset card itself evidences nothing — recorded as-is."),
    dict(ds="hishab/openbookqa-bn", family="OpenBookQA", langs=["bn"],
         kind="translation_of", parent="allenai/openbookqa", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/allenai/openbookqa",
         tt="machine", tt_ev=["card"],
         card_quote="The dataset was translated using a new method called Expressive Semantic Translation (EST), which combines Google Machine Translation with LLM-based rewriting modifications.",
         engine="Google Translate + LLM rewriting (EST; LLM unnamed)", engine_ev=["card"],
         verif="unknown", verif_note="no human-review statement (EST's rewriting stage is model-based)",
         kind_ev=["card"], license="unknown",
         license_note="hub metadata license tag is literally 'unknown'"),
    dict(ds="hishab/piqa-bn", family="PIQA", langs=["bn"],
         kind="translation_of", parent="ybisk/piqa", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/ybisk/piqa",
         tt="machine", tt_ev=["card"],
         card_quote="The dataset was translated using a new method called Expressive Semantic Translation (EST), which combines Google Translation with LLM-based rewriting.",
         engine="Google Translate + LLM rewriting (EST; LLM unnamed)", engine_ev=["card"],
         verif="unknown", verif_note="no human-review statement",
         kind_ev=["card"], license="mit", license_ev=["meta"]),
    dict(ds="hishab/commonsenseqa-bn", family="CommonsenseQA", langs=["bn"],
         kind="translation_of", parent="tau/commonsense_qa", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/tau/commonsense_qa",
         tt="machine", tt_ev=["card"],
         card_quote="The dataset was translated using a new method called **Expressive Semantic Translation (EST)**. This method combines both Google Machine Translation and LLM-based rewriting of the translation",
         engine="Google Translate + LLM rewriting (EST; LLM unnamed)", engine_ev=["card"],
         verif="unknown", verif_note="no human-review statement",
         kind_ev=["card"], license="mit", license_ev=["meta"]),
    dict(ds="hishab/boolq_bn", family="BoolQ", langs=["bn"],
         kind="modeled_on", parent="google/boolq",
         parent_url="https://huggingface.co/datasets/google/boolq",
         tt="lm_generated", tt_ev=["card"],
         card_quote="BoolQ Bangla (BN) is a question-answering dataset for yes/no questions, generated using GPT-4.",
         engine="GPT-4", engine_ev=["card"],
         verif="partial", verif_ev=["card2"],
         card2_quote="The dataset was manually reviewed by a human annotator (random samples), revealing an error rate of 1.33%, which was subsequently corrected.",
         verif_note="random-sample human review with corrections — a stated sample, not full coverage",
         kind_ev=["card"], license="mit", license_ev=["meta"],
         notes="Generated (not translated) Bangla BoolQ-style data; passages sourced per card."),
    dict(ds="csebuetnlp/xnli_bn", family="XNLI", langs=["bn"],
         kind="translation_of", parent="facebook/xnli", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/facebook/xnli",
         tt="machine", tt_ev=["card"],
         card_quote="The dataset curation procedure was the same as the XNLI dataset: we translated the MultiNLI training data using the English to Bangla translation mod[el]",
         engine="BanglaNMT English-to-Bangla model (Hasan et al., 2020; aclanthology 2020.emnlp-main.207)", engine_ev=["card"],
         verif="unknown",
         verif_note="split-level validation details live in the BanglaBERT paper; not stated in the card lines captured",
         kind_ev=["card"], license="cc-by-nc-sa-4.0", license_ev=["meta"]),
    dict(ds="csebuetnlp/squad_bn", family="SQuAD", langs=["bn"],
         kind="translation_of", parent="rajpurkar/squad_v2", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/rajpurkar/squad_v2",
         tt="mixed", tt_ev=["card"],
         card_quote="This is a Question Answering (QA) dataset for Bengali, curated from the SQuAD 2.0, TyDI-QA datasets and using the state-of-the-art English to Bengali translation model",
         card_note="'For the training set, we translated the complete SQuAD 2.0 dataset using the English to Bangla translation model' — machine-translated SQuAD plus curated TyDiQA-bn (natively written) items",
         engine="BanglaNMT English-to-Bangla model (translated portion)", engine_ev=["card"],
         verif="unknown", verif_note="no statement in captured card lines",
         kind_ev=["card"], license="cc-by-nc-sa-4.0", license_ev=["meta"]),
    dict(ds="KillerShoaib/DeepSeek-r1-Distill-Bangla-MMLU-Reasoning-Data", family="MMLU", langs=["bn"],
         kind="subset_or_filter_of", parent="hishab/bangla-mmlu",
         parent_url="https://huggingface.co/datasets/hishab/bangla-mmlu",
         tt="mixed", tt_ev=["card"],
         card_quote="to make this dataset completely in Bangla I need to translate it. For this I've used again Gemini flash 2.0.",
         card_note="native Bangla questions from hishab/bangla-mmlu + DeepSeek-R1-generated reasoning traces machine-translated to Bangla with Gemini Flash 2.0",
         engine="DeepSeek R1 (reasoning generation) + Gemini Flash 2.0 (translation to Bangla)", engine_ev=["card"],
         verif="none", verif_ev=["card2"],
         card2_quote="Instead of manually checking which answer was correct I use gemini flash 2.0 and automate the whole process.",
         verif_note="creator's own account affirms an automated-only checking pipeline",
         kind_ev=["card"], license="unknown",
         license_note="no license declared in hub metadata at the pinned revision",
         notes="A benchmark-derived SFT dataset; included to demonstrate lineage tracking into training-data derivatives."),
]

if __name__ == "__main__":
    written = write_records(SPECS)
    print(f"batch 3: {len(written)} records")
