# Batch 4 — remaining sampled rows: Italian/Spanish/Turkish/Greek/Basque/
# Romanian/Finnish/Persian/Odia variants, East Asia natives, minimal-card rows.
# Curator judgments (2026-08-24) over pinned snapshots + cited papers/pages.
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from make_records import load_snapshot, write_records  # noqa: E402


def yaml_langs(ds, drop=("en", "code")):
    langs = load_snapshot(ds)["hub_metadata"]["cardData_language"] or []
    if isinstance(langs, str):
        langs = [langs]
    return [l for l in langs if l not in drop]


MLMM_QUOTE = ("These datasets are translated from the original ARC, HellaSwag, and MMLU "
              "datasets in English using ChatGPT.")

SPECS = [
    dict(ds="s-conia/mmlu_italian", family="MMLU", langs=["it"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", tt_ev=["card"],
         card_quote="Model used: `gpt-4o-mini-2024-07-18`",
         card_note="OBenTO open-LLM translation process; 'some instances were filtered' during translation",
         engine="gpt-4o-mini-2024-07-18", engine_ev=["card"],
         verif="unknown", verif_note="no human-review statement; filtering described as part of the automated process",
         kind_ev=["card"], license="cc-by-nc-sa-4.0", license_ev=["meta"]),
    dict(ds="sapienzanlp/mmlu_italian", family="MMLU", langs=["it"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", tt_ev=["card"],
         card_quote="Model used to translate: Unbabel/TowerInstruct-7B-v0.2",
         engine="Unbabel/TowerInstruct-7B-v0.2", engine_ev=["card"],
         verif="unknown", verif_note="no human-review statement",
         kind_ev=["card"], license="cc-by-nc-sa-4.0", license_ev=["meta"],
         notes="Second independent Italian MMLU translation (OBenTO-LLM lineage), distinct engine from s-conia/mmlu_italian."),
    dict(ds="alvarobartt/mmlu-okapi-eval-es", family="MMLU", langs=["es"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", tt_ev=["card", "meta_tags"],
         card_quote="they used the original MMLU dataset in English and translated it into different languages using ChatGPT. This dataset only contains the Spanish translation",
         meta_tags_quote="tags: chatgpt-translated",
         engine="ChatGPT (University of Oregon / Okapi translations)", engine_ev=["card"],
         verif="unknown", verif_note="no human-review statement",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"]),
    dict(ds="OpenLLM-Ro/ro_hellaswag", family="HellaSwag", langs=["ro"],
         kind="translation_of", parent="Rowan/hellaswag", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/Rowan/hellaswag",
         tt="machine", tt_ev=["card", "content"],
         card_quote="Here we provide the Romanian translation of the Hellaswag from the paper \"Okapi[...]\"",
         content_url="https://github.com/nlp-uoregon/mlmm-evaluation/blob/main/README.md",
         content_quote=MLMM_QUOTE,
         content_note="the Okapi/mlmm project the card cites documents ChatGPT translation for its HellaSwag sets",
         engine="ChatGPT (Okapi translations)", engine_ev=["content"],
         verif="unknown", verif_note="no human-review statement",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"]),
    dict(ds="ilsp/hellaswag_greek", family="HellaSwag", langs=["el"],
         kind="translation_of", parent="Rowan/hellaswag", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/Rowan/hellaswag",
         tt="machine", tt_ev=["card"],
         card_quote="The HellaSwag Greek dataset is a set of 59832 examples from the HellaSwag dataset, machine-translated into Greek.",
         engine="unknown", engine_note="no engine named in the card",
         verif="unknown", verif_note="no statement",
         kind_ev=["card"], license="cc-by-nc-sa-4.0", license_ev=["meta"]),
    dict(ds="orai-nlp/HellaSwag_HT_eu_sample", family="HellaSwag", langs=["eu"],
         kind="translation_of", parent="Rowan/hellaswag", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/Rowan/hellaswag",
         tt="human", tt_ev=["card"],
         card_quote="A subset of 250 samples manually translated to Basque from the HellaSwag dataset (Zellers et al., 2019).",
         engine="Orai NLP Teknologiak (manual translation)", engine_ev=["card"],
         verif="unknown", verif_note="human translation by construction; no separate QA step stated",
         kind_ev=["card"], license="cc-by-nc-sa-4.0", license_ev=["meta"],
         notes="250-sample human-translated Basque subset — a deliberate small HT contrast to the MT variants."),
    dict(ds="Patt/HellaSwag_TH_cleanned", family="HellaSwag", langs=["th"],
         kind="translation_of", parent="Rowan/hellaswag", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/Rowan/hellaswag",
         tt="machine", tt_ev=["card"],
         card_quote="This dataset is Thai translated version of hellaswag using google translate with Multilingual Universal Sentence Encoder to calculate score",
         engine="Google Translate (+MUSE-score auto-filtering)", engine_ev=["card"],
         verif="none", verif_ev=["card2"],
         card2_quote="The score was penalized by the length of original text compare to translated text. The row that any score < 0.5 was dropped.",
         verif_note="the card describes a fully automated translate-score-filter pipeline; QC is automatic, not human",
         kind_ev=["card"], license="cc-by-sa-4.0", license_ev=["meta"]),
    dict(ds="malhajar/arc-tr", family="ARC", langs=["tr"],
         kind="translation_of", parent="allenai/ai2_arc", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/allenai/ai2_arc",
         tt="unknown", engine="unknown",
         tt_note="the card states it is 'a translated version of arc' but no method (machine vs human); note: sibling dataset malhajar/mmlu_tr-v0.2 documents GPT-4, but no such statement exists here",
         engine_note="not stated",
         verif="unknown", verif_note="no statement",
         kind_ev=["card"],
         card_quote="malhajar/arc-tr is a translated version of arc aimed specifically to be used in the OpenLLMTurkishLeaderboard",
         license="mit", license_ev=["meta"],
         notes="Card misuses 'annotations_creators: found' for a translated set — an example of hub-tag noise."),
    dict(ds="NovusResearch/gsm8k-Translated-TR", family="GSM8K", langs=["tr"],
         kind="translation_of", parent="openai/gsm8k", src="unknown",
         src_note="nothing but the dataset name asserts anything; source language unstated",
         parent_url="https://huggingface.co/datasets/openai/gsm8k",
         tt="unknown", engine="unknown",
         tt_note="the card contains only 'license: mit'; the id 'gsm8k-Translated-TR' is the only provenance signal",
         engine_note="not stated",
         verif="unknown", verif_note="no statement",
         kind_ev=["name"], name_note="dataset id: NovusResearch/gsm8k-Translated-TR (name is the only derivation evidence)",
         license="mit", license_ev=["meta"],
         notes="Target language tr taken from the dataset id; a minimal-provenance showcase row."),
    dict(ds="universitytehran/MMLUAuxiliary", family="MMLU", langs=["fa"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="unknown", engine="unknown",
         tt_note="'This is a Persian translation of auxiliary_train split of MMLU dataset.' — no method stated",
         engine_note="not stated",
         verif="unknown", verif_note="no statement",
         kind_ev=["card"],
         card_quote="This is a Persian translation of `auxiliary_train` split of MMLU dataset.",
         license="unknown", license_note="no license declared in hub metadata at the pinned revision"),
    dict(ds="lrana/MMLU_ita", family="MMLU", langs=["it"],
         kind="translation_of", parent="cais/mmlu", src="unknown",
         src_note="not stated; the card is an unfilled template",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="unknown", engine="unknown",
         tt_note="the card is the default template with '[More Information Needed]' placeholders throughout",
         engine_note="not stated",
         verif="unknown", verif_note="no statement",
         kind_ev=["name"], name_note="dataset id 'MMLU_ita' with language tag it; no prose evidence",
         license="unknown", license_note="no license declared in hub metadata at the pinned revision"),
    dict(ds="mizinovmv/ru_cais_mmlu", family="MMLU", langs=["ru"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="unknown", engine="unknown",
         tt_note="the card is YAML-only; feature names (question_en/choices_en alongside Russian fields) show a translation-pair structure but no method",
         engine_note="not stated",
         verif="unknown", verif_note="no statement",
         kind_ev=["card"],
         card_quote="features: - name: question_en dtype: string - name: subject dtype: string - name: choices_en sequence: string",
         card_note="YAML features evidence a ru/en parallel structure; dataset id references cais/mmlu",
         license="apache-2.0", license_ev=["meta"]),
    dict(ds="ik-ram28/fr-mmlu_professional_medicine", family="MMLU", langs=["fr"],
         kind="translation_of", parent="cais/mmlu", src="unknown",
         src_note="not stated in the YAML-only card",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="unknown", engine="unknown",
         tt_note="YAML-only card; 'question_translated'/'options_translated' features prove a translation exists, method unstated",
         engine_note="not stated",
         verif="unknown", verif_note="no statement",
         kind_ev=["card"],
         card_quote="- name: question_translated dtype: string - name: options_translated struct:",
         license="unknown", license_note="no license declared in hub metadata at the pinned revision"),
    dict(ds="Slim205/mmlu_translated_nllb0", family="MMLU", langs=["ar"],
         kind="translation_of", parent="cais/mmlu", src="en",
         src_ev=["content"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", tt_ev=["name"],
         name_note="dataset id contains 'translated_nllb0'; NLLB is a machine-translation model family",
         engine="NLLB (per dataset name only)", engine_ev=["name"],
         verif="unknown", verif_note="no statement; the card is YAML-only",
         kind_ev=["content"],
         content_url="https://datasets-server.huggingface.co/first-rows?dataset=Slim205%2Fmmlu_translated_nllb0&config=default&split=auxiliary_train",
         content_quote="\"question\": \"Davis decided to kill Adams. [...]\" / \"translated_question\": \"قرر ديفيس قتل آدامز. [...]\"",
         content_note="first rows show English MMLU items with Arabic translations — target language ar established by content",
         license="unknown", license_note="no license declared in hub metadata",
         notes="Engine attribution rests on the dataset name alone (claim status name_only)."),
    dict(ds="Slim205/mmlu_ift_256_translated_nllb0", family="MMLU", langs=["ar"],
         kind="translation_of", parent="cais/mmlu", src="en",
         src_ev=["content"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="machine", tt_ev=["name"],
         name_note="dataset id contains 'translated_nllb0'",
         engine="NLLB (per dataset name only)", engine_ev=["name"],
         verif="unknown", verif_note="no statement; YAML-only card",
         kind_ev=["content"],
         content_url="https://datasets-server.huggingface.co/first-rows?dataset=Slim205%2Fmmlu_ift_256_translated_nllb0&config=default&split=auxiliary_train",
         content_quote="\"translated_instruction\": \"قواعد غرفة القراءة مرحبًا بكم جميعاً. [...]\"",
         content_note="first rows show Arabic translations of MMLU auxiliary_train items with added IFT fields",
         license="unknown", license_note="no license declared in hub metadata",
         notes="IFT-augmented variant; engine attribution rests on the name alone."),
    dict(ds="Translated-MMLU-Blind-Review/ACL-SRW-2025", family="MMLU", langs=["pt"],
         kind="translation_of", parent="cais/mmlu", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="mixed", tt_ev=["card"],
         card_quote="**translation_method** `English`, `Google Translate`, `GPT-3.5-Turbo`, `GPT-4o`, `Human`",
         card_note="research artifact comparing translation methods; every item carries its method",
         engine="Google Translate / GPT-3.5-Turbo / GPT-4o / human (per item)", engine_ev=["card"],
         verif="per_item_flags", verif_ev=["card"],
         verif_note="the per-item translation_method column distinguishes the Human arm from machine arms",
         per_item=dict(field="translation_method",
                       description="per-item translation method: English (original) / Google Translate / GPT-3.5-Turbo / GPT-4o / Human"),
         kind_ev=["card"], license="gpl-3.0", license_ev=["meta"],
         notes="ACL SRW 2025 study of MMLU translation variability (en→pt); the only per-item method column found outside Global-MMLU in the seed sweep."),
    dict(ds="taresco/COHERE-GLOBAL-MMLU-FILTERED-MATH", family="MMLU",
         langs=yaml_langs("taresco/COHERE-GLOBAL-MMLU-FILTERED-MATH"),
         kind="subset_or_filter_of", parent="CohereLabs/Global-MMLU",
         parent_url="https://huggingface.co/datasets/CohereLabs/Global-MMLU",
         tt="mixed", tt_ev=["card"],
         card_quote="- name: cultural_sensitivity_label dtype: string - name: is_annotated dtype: bool",
         card_note="the YAML schema preserves Global-MMLU's per-item fields, evidencing the subset relationship; creation method is the parent's (MT + professional + crowd post-edits)",
         engine="Google Translate API (machine-translated portion, per parent)", engine_ev=["ext"],
         ext_url="https://arxiv.org/html/2412.03304",
         ext_quote="We first translated the English MMLU dataset into 41 languages using the Google Translate API.",
         ext_note="parent dataset's paper; this subset inherits those items",
         verif="per_item_flags", verif_ev=["card"],
         per_item=dict(field="is_annotated",
                       description="inherited Global-MMLU per-item human-edit flag"),
         kind_ev=["card"], license="apache-2.0", license_ev=["meta"],
         notes="Math-subject, African-language-focused filter of Global-MMLU."),
    dict(ds="Finnish-NLP/belebele-fi-filtered-sft", family="Belebele", langs=["fi"],
         kind="subset_or_filter_of", parent="facebook/belebele",
         parent_url="https://huggingface.co/datasets/facebook/belebele",
         tt="human", tt_ev=["ext"],
         ext_url="https://huggingface.co/datasets/facebook/belebele/raw/7899cdfa4e4e63b06556ba9dceabb58bc3e17b10/README.md",
         ext_quote="Belebele is a multiple-choice machine reading comprehension (MRC) dataset spanning 122 language variants.",
         ext_note="parent card; Belebele's items are professionally translated (see facebook-belebele__mul record). Applies to the items this dataset's name asserts it derives from",
         engine="Language Service Provider (professional, unnamed; per parent)", engine_ev=["ext"],
         verif="unknown",
         verif_note="parent had QA loops; whether filtering preserved anything verification-relevant is unstated",
         kind_ev=["name"],
         name_note="dataset id 'belebele-fi-filtered-sft'; its own card carries no prose about derivation",
         license="cc-by-sa-4.0", license_ev=["meta"],
         notes="Derivation rests on the dataset's name (claim status name_only); translation facts inherited from the parent under that assumption — see kind claim status."),
    dict(ds="Ashmal/MMLU_SyntheticData", family="MMLU", langs=["ar"],
         kind="modeled_on", parent="MBZUAI/ArabicMMLU",
         parent_url="https://huggingface.co/datasets/MBZUAI/ArabicMMLU",
         tt="lm_generated", tt_ev=["card"],
         card_quote="MMLU_SyntheticData is generated using GPT-4. ... Please note that this is not the translated version of MMLU, it's an entirely independent dataset.",
         card_note="'The subjects (above) are taken from the ArabicMMLU Dataset'",
         engine="GPT-4", engine_ev=["card"],
         verif="unknown", verif_note="no human-review statement",
         kind_ev=["card"], license="apache-2.0", license_ev=["meta"],
         notes="Synthetic Arabic MMLU-style data; explicitly NOT a translation — the card says so itself."),
    dict(ds="alibayram/turkish_mmlu", family="MMLU", langs=["tr"],
         kind="modeled_on", parent="cais/mmlu",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="native_original", tt_ev=["meta_tags"],
         meta_tags_quote="pretty_name: 'Turkish MMLU: Yapay Zeka ve Akademik Uygulamalar İçin En Kapsamlı ve Özgün Türkçe Veri Seti'",
         meta_tags_note="'Özgün Türkçe Veri Seti' = original/authentic Turkish dataset (exam-derived questions, per card's Zenodo record)",
         kind_ev=["meta_tags"],
         license="cc-by-nc-nd-4.0", license_ev=["meta"],
         license_conflicts=[dict(value="cc-by-nc-4.0 (card prose)", ev=["card"],
                                 note="card text states CC BY-NC 4.0 while the hub tag declares cc-by-nc-nd-4.0 (adds ND)")],
         card_quote="Bu veri seti, Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) lisansı altında lisanslanmıştır.",
         notes="Gated dataset (card URL requires an authenticated, condition-accepting session). The hub license tag and the card prose disagree — both positions preserved."),
    dict(ds="HAERAE-HUB/KMMLU", family="MMLU", langs=["ko"],
         kind="modeled_on", parent="cais/mmlu",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="native_original", tt_ev=["card"],
         card_quote="Unlike previous Korean benchmarks that are translated from existing English benchmarks, KMMLU is collected from original Korean exams, capturing linguistic and cultural aspects of the Korean language.",
         kind_ev=["card"], license="cc-by-nd-4.0", license_ev=["meta"],
         notes="Native Korean exam benchmark, created explicitly in contrast to translated variants."),
    dict(ds="haonan-li/cmmlu", family="MMLU", langs=["zh"],
         kind="modeled_on", parent="cais/mmlu",
         parent_url="https://huggingface.co/datasets/cais/mmlu",
         tt="native_original", tt_ev=["card"],
         card_quote="Many of these tasks are not easily translatable from other languages due to their specific contextual nuances and wording.",
         card_note="subjects include chinese_history, modern_chinese, traditional_chinese_medicine — Chinese-original content per the CMMLU paper (arXiv:2306.09212)",
         kind_ev=["card"], license="cc-by-nc-4.0", license_ev=["meta"]),
    dict(ds="meta-math/GSM8K_zh", family="GSM8K", langs=["zh"],
         kind="translation_of", parent="openai/gsm8k", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/openai/gsm8k",
         tt="machine", tt_ev=["card"],
         card_quote="question-answer pairs are translated from GSM8K by `GPT-3.5-Turbo` with few-shot prompting.",
         engine="GPT-3.5-Turbo (few-shot prompting)", engine_ev=["card"],
         verif="unknown", verif_note="no human-review statement",
         kind_ev=["card"], license="mit", license_ev=["meta"]),
    dict(ds="DoggiAI/GSM8K_zh_tw", family="GSM8K", langs=["zh-Hant"],
         kind="script_conversion_of", parent="meta-math/GSM8K_zh", src="zh", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/meta-math/GSM8K_zh",
         tt="script_conversion", tt_ev=["card"],
         card_quote="It is derived from the GSM8K_zh dataset by translating question-answer pairs into Traditional Chinese using OpenCC.",
         engine="OpenCC", engine_ev=["card"],
         verif="unknown",
         verif_note="'the dataset includes modifications' beyond conversion per the card; no review statement",
         kind_ev=["card"], license="mit", license_ev=["meta"],
         notes="Deterministic Simplified→Traditional conversion; the upstream Chinese text is itself machine-translated (see parent record)."),
    dict(ds="ryota39/gsm8k-ja", family="GSM8K", langs=["ja"],
         kind="translation_of", parent="openai/gsm8k", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/openai/gsm8k",
         tt="machine", tt_ev=["card"],
         card_quote="openai/gsm8kをopenai/gpt-oss-120bで翻訳したデータセットです。",
         card_note="Japanese: 'a dataset translated from openai/gsm8k with openai/gpt-oss-120b'",
         engine="gpt-oss-120b", engine_ev=["card"],
         verif="unknown", verif_note="no statement",
         kind_ev=["card"], license="apache-2.0", license_ev=["meta"]),
    dict(ds="tripathysagar/odia-truthfulqa-mc", family="TruthfulQA", langs=["or"],
         kind="translation_of", parent="truthfulqa/truthful_qa", src="en", src_ev=["card"],
         parent_url="https://huggingface.co/datasets/truthfulqa/truthful_qa",
         tt="machine", tt_ev=["card"],
         card_quote="OdiaBench translations were produced via Cursor subagents (Composer 2.5-fast) using",
         card_note="'Questions and gold answers are translated; distractor choices in mc1_choices remain in English.'",
         engine="Cursor subagents (Composer 2.5-fast)", engine_ev=["card"],
         verif="unknown", verif_note="no human-review statement in captured lines",
         kind_ev=["card"], license="apache-2.0", license_ev=["meta"],
         notes="Partial translation scope: distractor options remain English — a provenance detail consumers would want."),
]

if __name__ == "__main__":
    written = write_records(SPECS)
    print(f"batch 4: {len(written)} records")
